services:
  db:
    image: postgres:16
    container_name: komado-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: komado
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - komado-postgres-data:/var/lib/postgresql/data

  mailpit:
    image: axllent/mailpit:v1.21.4
    container_name: komado-mailpit
    restart: unless-stopped
    ports:
      - "8025:8025"
      - "1025:1025"

volumes:
  komado-postgres-data:
